title: Kai Berezniak # your name (or website title) here
logo: "/images/ProfesionalSS.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <br>
  in _config.yml 
  <br><br>
  <a href="https://www.linkedin.com/in/kayetan-berezniak-a85578265/" target="_blank">LinkedIn</a>
  <br>
  <a href="{{ '/assets/Kayetan_Berezniak_Resume.html' | relative_url }}"
     class="btn btn--info" target="_blank">
    Resume
  </a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">GitHub</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Twitter</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">Youtube</a> 
  
theme: jekyll-theme-minimal
